# Generated by Django 4.2.6 on 2023-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astute_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='coordinates_horizontal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='coordinates_vertical',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
