# Generated by Django 4.2.6 on 2023-10-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astute_backend', '0002_alter_good_category_alter_good_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='active',
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.RemoveField(
            model_name='good',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='good',
            name='coordinates_horizontal',
        ),
        migrations.RemoveField(
            model_name='good',
            name='coordinates_vertical',
        ),
        migrations.RemoveField(
            model_name='good',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='good',
            name='description',
        ),
        migrations.RemoveField(
            model_name='good',
            name='name',
        ),
    ]
