# Generated by Django 4.2.6 on 2023-10-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astute_backend', '0003_remove_good_active_remove_good_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='good',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='good',
            name='coordinates_horizontal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='coordinates_vertical',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
