# Generated by Django 4.2.6 on 2023-10-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astute_backend', '0005_alter_good_coordinates_horizontal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('coordinates_vertical', models.FloatField(blank=True, null=True)),
                ('coordinates_horizontal', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='coordinates_horizontal',
        ),
        migrations.RemoveField(
            model_name='good',
            name='coordinates_vertical',
        ),
        migrations.AddField(
            model_name='good',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='astute_backend.location'),
        ),
    ]
