# Generated by Django 4.2.6 on 2023-10-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astute_backend', '0006_location_remove_good_coordinates_horizontal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astute_backend.locationtype'),
        ),
    ]
